/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e7eeff",
        "secondary": "#006c49",
        "tertiary": "#8e3c00",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-highest": "#d8e3fb",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary-fixed": "#341100",
        "surface-dim": "#cfdaf2",
        "tertiary-fixed-dim": "#ffb690",
        "primary-fixed": "#dbe1ff",
        "secondary-container": "#6cf8bb",
        "on-primary-container": "#eeefff",
        "on-tertiary-container": "#ffece5",
        "primary-fixed-dim": "#b4c5ff",
        "on-surface-variant": "#434655",
        "on-surface": "#111c2d",
        "surface-variant": "#d8e3fb",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#00714d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "on-error-container": "#93000a",
        "surface": "#f9f9ff",
        "tertiary-container": "#b54e00",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbca",
        "surface-container-high": "#dee8ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "primary-container": "#2563eb",
        "inverse-surface": "#263143",
        "on-primary-fixed": "#00174b",
        "on-background": "#111c2d",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "primary": "#004ac6",
        "background": "#f9f9ff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#783200",
        "on-primary": "#ffffff",
        "surface-tint": "#0053db",
        "outline": "#737686",
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
